#ifndef CONSTS
#define ACTIVATIONS_WIDTH 28
#define ACTIVATIONS_HEIGHT 28
#define NUM_ACTIVATION_NEURONS ACTIVATIONS_WIDTH * ACTIVATIONS_HEIGHT
#define NUM_LAYER0_NEURONS 16
#define NUM_LAYER1_NEURONS 16
#define NUM_OUTPUT_NEURONS 10
#endif
